forge 'http://forge.puppetlabs.com'

# Local modules
mod 'apache', :local =>true
mod 'php', :local =>true
mod 'mariadb', :local =>true
mod 'baseconfig', :local =>true

# Modules discovered by generate-puppetfile
mod 'puppetlabs/mysql'
mod 'puppetlabs/concat'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/vcsrepo'
